<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email' => '',
    'Hash' => '',
    'ID' => '',
    'Page ID' => 'Stránka',
    'Parent Category ID' => 'Nadřazená rubrika',
    'Time stamp for order' => 'Časové razítko pro řazení',
    'Acronym' => 'Zkratka',
    'Active' => 'Aktivní',
    'Additional field ID' => 'ID doplňkového pole',
    'Administrator' => 'Administrátor',
    'Answer' => 'Odpověď',
    'Article' => 'Článek',
    'Authenticated user' => 'Přihlášený uživatel',
    'Category' => 'Rubrika',
    'Category Type' => 'Typ kategorie',
    'Content' => 'Obsah',
    'Content Type' => 'Typ obsahu',
    'Created At' => 'Vytvořeno',
    'Created By' => 'Vytvořil',
    'Date' => 'Datum',
    'Description' => 'Popis',
    'Editor' => 'Redaktor',
    'Editor in chief' => 'Šéfredaktor',
    'Editor of dishes' => 'Správce jídelníčků',
    'End date' => 'Koncové datum',
    'Field content' => 'Obsah pole',
    'Field label' => 'Název pole',
    'File' => 'Soubor',
    'Filename' => 'Název souboru',
    'Frequency' => 'Četnost',
    'Gallery' => 'Galerie',
    'Image' => 'Obrázek',
    'Image filename' => 'Jméno souboru obrázku',
    'Inactive' => 'Neaktivní',
    'Incorrect username or password.' => 'Špatné uživatelské jméno nebo heslo.',
    'Items order' => 'Pořadí položek',
    'Language' => 'Jazyk',
    'Language ID' => 'ID jazyka',
    'Layout' => 'Šablona',
    'Link Target' => 'Cíl odkazu',
    'Link Url' => 'URL odkazu',
    'Main' => 'Hlavní',
    'Main layout not exists!' => 'Hlavní šablona neexistuje',
    'Menu ID' => 'ID menu',
    'Menu Item' => 'Položka menu',
    'Modification time of file' => 'Čas poslední úpravy souboru',
    'Name' => 'Název',
    'Newsletter' => 'Novinky emailem',
    'Order' => 'Pořadí',
    'Page' => 'Stránka',
    'Parent Item ID' => 'ID položky menu',
    'Password' => 'Heslo',
    'Perex' => 'Upoutávka',
    'Poll ID' => 'Anketa',
    'Properties' => 'Vlastnosti',
    'Public' => 'Veřejné',
    'Question' => 'Otázka',
    'Remember Me' => 'Zapamatuj si mne',
    'Status' => 'Stav',
    'Tags' => 'Štítky',
    'Text ID' => 'Textové ID',
    'Theme' => 'Motiv',
    'Time' => 'Čas',
    'Title' => 'Název',
    'Type' => 'Typ',
    'Updated At' => 'Změněno',
    'Updated By' => 'Změnil',
    'Username' => 'Uživatel',
    'Voices' => 'Hlasy',
    'Web ID' => 'ID webu',
    'files' => 'soubory',
    'images' => 'obrázky',
    'sounds' => 'zvuky',
];
