<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The requested page does not exist.' => 'Požadovaná stránka neexistuje',
    'You have really very <strong>old</strong> web browser. Please <a
	href="http://browsehappy.com/">upgrade</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate
	Google Chrome Frame</a> for better experinece.' => 'Máte opravdu hodně <strong>starý</strong> webový prohlížeč. Prosíme <a href="http://browsehappy.com/">nainstalujte si</a> jeho vyšší verzi nebo <a href="http://www.google.com/chromeframe/?redirect=true">si aktivujte Google Chrome Frame</a> pro lepší zážitky.',
    'show - hide search window' => 'zobrazit - skrýt okno pro vyhledávání',
    'Agree with sending of newsletter' => 'Souhlasím se zasíláním novinek',
    'Articles' => 'Články',
    'Business hours' => 'Provozní doba',
    'Close' => 'Zavřít',
    'Contact form' => 'Kontaktní formulář',
    'Contacts' => 'Kontakty',
    'Email not found.' => 'Email nenalezen.',
    'Got It' => 'Rozumím',
    'If you want to send some message to us, you can use next form:' => 'Pokud nám chcete poslat nějakou zprávu, můžete použít tento formulář:',
    'Image' => 'Obrázek',
    'Message from site www.dasport.cz' => 'Zpráva z webu www.dasport.cz',
    'More info' => 'Více informací',
    'Most used tags' => 'Nejpoužívanější štítky',
    'Newsletter subscribe' => 'Přihlášení novinek emailem',
    'Newsletter unsubscribe' => 'Odhlášení novinek emailem',
    'Next pages in menu' => 'Další stránky v nabídce',
    'No required parameter given' => 'Nebyl předán povinný parametr',
    'Please contact us if you think this is a server error. Thank you.' => 'Prosím kontaktujte nás, pokud se domníváte, že jde o chybu. Díky.',
    'Poll' => 'Anketa',
    'Pretender email' => 'Email žadatele',
    'Pretender message' => 'Zpráva',
    'Pretender name' => 'Jméno žadatele',
    'Print to PDF' => 'Tisk do PDF',
    'Recent articles' => 'Poslední články',
    'Recent articles in category' => 'Poslední články v rubrice',
    'Search results' => 'Výsledky hledání',
    'Search results against tag' => 'Výsledky hledání podle štítku',
    'Search results for expression' => 'Výsledky hledání pro výraz',
    'Search results for tag' => 'Výsledky hledání pro štítek',
    'Search this site' => 'Prohledat tento web',
    'Searched expression' => 'Hledaný výraz',
    'Share on facebook' => 'Sdílet na facebooku',
    'Share on google+' => 'Sdílet na google+',
    'Share on twitter' => 'Sdílet na twitteru',
    'Skip to gallery' => 'Přejít do galerie',
    'Submit' => 'Odeslat',
    'Subpages' => 'Podstránky',
    'Target of searching' => 'Cíl hledání',
    'Thank you for subscription of our newsletter.' => 'Děkujeme za přihlášení novinek emailem.',
    'Thank you for subscription request of our newsletter.' => 'Děkujeme za Váš požadavek na přihlášení novinek.',
    'The above error occurred while the Web server was processing your request.' => 'Při zpracování Vašeho požadavku se vyskytla výše uvedená chyba.',
    'This email is already in use.' => 'Tento email je již použit.',
    'This website uses cookies to ensure you get the best experience on our website.' => 'Tento web využívá cookies. Jeho používáním s tím vyjadřujete souhlas.',
    'To confirm please click this link' => 'Pro potvrzení klikněte na následující odkaz',
    'Unknown sound file' => 'Neznámý zvukový soubor',
    'Used tags' => 'Použité štítky',
    'Verify code' => 'Ověřovací kód',
    'Vote' => 'Hlasovat',
    'We have no actualities at this time.' => 'V systému nyní nejsou žádné aktuality.',
    'We have no invitations at this time.' => 'V systému nyní nejsou žádné pozvánky.',
    'We regret that you unsubscribe our newsletter.' => 'Je nám líto, že odhlašujete novinky emailem.',
    'You must agree with newsletter subscription.' => 'Je potřeba vyjádřit souhlas se zasíláním novinek.',
    'Your email' => 'Váš email',
    'Your full name' => 'Vaše celé jméno',
    'Your message' => 'Vaše zpráva',
    'Your message was successfuly submitted. Thank you!' => 'Vaše zpráva byla úspěšně odeslána. Děkujeme!',
    'Your unsubscription request was sent.' => 'Váš požadavek na odhlášení byl odeslán.',
    'answer' => 'odpověď',
    'close' => 'zavřít',
    'details' => 'detaily',
    'flag' => 'vlajka',
    'home' => 'domů',
    'our contacts' => 'naše kontakty',
    'to top' => 'nahoru',
    'voices' => 'hlasy',
    'vote' => 'hlasovat',
];
