<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Albert 5 CMS' => '',
    'Main category record not available!' => 'Hlavní rubrika není k dispozici.',
    'default' => 'nezařazené',
    'email' => '',
    'ok' => '',
    'password' => 'heslo',
    'username' => 'uživatel',
    'Article with main image' => 'Článek s úvodním obrázkem',
    'CMS is already installed!' => 'Redakční systém je již nainstalován!',
    'Category with pagination' => 'Rubrika se stránkováním',
    'Content of home page.' => 'Obsah úvodní stránky',
    'Default article' => 'Běžný článek',
    'Default category' => 'Běžná rubrika',
    'Default count of displayed tags' => 'Počet zobrazovaných štítků',
    'Default page' => 'Běžná stránka',
    'Email for contact form' => 'Email pro kontaktní formulář',
    'Email of newsletter sender' => 'Email newsletteru (odesílatel)',
    'Email of webmaster' => 'Email webmastera',
    'Gallery link image size' => 'Velikost obrázku odkazu na galerii (box)',
    'Gallery thumbnail size' => 'Velikost náhledu obrázku galerie',
    'Google maps key' => 'Klíč google map',
    'Home page' => 'Úvodní stránka',
    'Homepage' => 'Úvodní stránka',
    'Homepage record not available!' => 'Záznam pro úvodní stránku není k dispozici!',
    'Invitations' => 'Pozvánky',
    'Invitations archive' => 'Archiv pozvánek',
    'Layout\'s don\'t exist!' => 'Šablony neexitují!',
    'Main language (frontend and backend)' => 'Hlavní jazyk (frontend and backend)',
    'Main language record not available!' => 'Záznam pro hlavní jazyk není k dispozici!',
    'Main menu item record not available!' => 'Záznam pro hlavní položku menu není k dispozici!',
    'Main menu record not available!' => 'Záznam pro hlavní menu není k dispozici!',
    'Main web record not available!' => 'Záznam pro hlavní web není k dispozici!',
    'Maximal width of image in content' => 'Maximální šířka obrázku v obsahu',
    'Name of main web' => 'Jméno hlavního webu',
    'Owner of web' => 'Vlastník webu',
    'Please fill out the following fields to create admin user' => 'Pro vytvoření administrátora vyplňte následující údaje',
    'Please fill out the following fields to create web application' => 'Pro vytvoření webové aplikace vyplňte následující údaje',
    'Please fill out the following fields to setup frontend application' => 'Pro nastavení frontendu vyplňte následující údaje',
    'Some highlight text.' => 'Text pro úvodník.',
    'Step of tag item font size' => 'Krok nastavení velikosti fontu štítku',
    'This action is not allowed!' => 'Tato akce není dovolena!',
    'Title of newsletter email (subject)' => 'Titulek mailu newsletteru (předmět)',
    'admin user creation' => 'vytvoření administrátora',
    'back' => 'zpět',
    'czech' => 'čeština',
    'english' => 'angličtina',
    'frontend settings' => 'nastavení frontendu',
    'home' => 'úvod',
    'main menu' => 'hlavní menu',
    'next' => 'další',
    'web creation' => 'vytvoření webu',
];
